version: '3'
services:
    web-order-system:
        container_name: oniad-order-system-web
        image: nginx
        volumes:
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ..:/var/www/html
            - ../logs/nginx/:/var/log/nginx/
        restart: always
        depends_on:
            - php-order-system
    php-order-system:
        container_name: oniad-order-system-php
        build:
          context: .
          dockerfile: ./conf/Dockerfile.dev
        restart: always
        user: 1000:1000
        volumes:
            - ./conf/php/php.dev.ini:/usr/local/etc/php/conf.d/php.ini
            - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ..:/var/www/html
    db-order-system:
        container_name: oniad-order-system-db
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5456:5432
        volumes:
            - ./conf/postgres/:/docker-entrypoint-initdb.d/