FROM php:8.1-fpm


RUN apt-get update \
    && apt-get install -y \
        apt-utils \
    && apt-get install -y \
        libpq-dev \
        libzip-dev \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install -j$(nproc) zip \
    && docker-php-ext-install -j$(nproc) pgsql \
    && docker-php-ext-install -j$(nproc) pdo_pgsql \
    && docker-php-ext-install mysqli

RUN apt-get install libcurl4-openssl-dev
RUN apt-get install  curl &&\
    docker-php-ext-install curl

# file permission acl
RUN apt-get install acl

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer